import React, { useState, useRef, useEffect } from 'react';
import axios from 'axios';
import { FiSend, FiCommand, FiTrash2 } from 'react-icons/fi';
import MessageBubble from './MessageBubble';

const ChatBox = ({ hasDocuments, onClearMemory }) => {
  const [messages, setMessages] = useState([
    { role: 'ai', content: 'Hello! I am DocuChat AI. Upload a PDF document and ask me anything about it.', sources: [] }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [sessionId, setSessionId] = useState(localStorage.getItem('docuchat_session_id') || null);
  const messagesEndRef = useRef(null);

  const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const handleSend = async (e) => {
    e.preventDefault();
    if (!input.trim()) return;

    // Check if documents are uploaded
    if (!hasDocuments) {
      setMessages(prev => [
        ...prev,
        { role: 'user', content: input },
        { role: 'error', content: 'Please upload a PDF document before asking questions.' }
      ]);
      setInput('');
      return;
    }

    const userMessage = input.trim();
    setInput('');
    setIsLoading(true);

    // Add user message immediately
    setMessages((prev) => [...prev, { role: 'user', content: userMessage }]);

    try {
      const response = await axios.post(`${API_URL}/chat`, {
        question: userMessage,
        session_id: sessionId
      });

      // Save new session_id if generated by backend
      if (response.data.session_id && !sessionId) {
        setSessionId(response.data.session_id);
        localStorage.setItem('docuchat_session_id', response.data.session_id);
      }

      setMessages((prev) => [
        ...prev,
        {
          role: 'ai',
          content: response.data.answer,
          sources: response.data.sources
        }
      ]);
    } catch (error) {
      console.error('Chat error:', error);
      setMessages((prev) => [
        ...prev,
        {
          role: 'error',
          content: error.response?.data?.detail || 'Sorry, I encountered an error while processing your request.',
          sources: []
        }
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  const clearChat = async () => {
    try {
      await axios.post(`${API_URL}/clear-memory`);
      setSessionId(null);
      localStorage.removeItem('docuchat_session_id');
      setMessages([{ role: 'ai', content: 'Conversation memory cleared. How can I help you today?', sources: [] }]);
      if (onClearMemory) onClearMemory();
    } catch (error) {
      console.error("Failed to clear memory");
    }
  };

  return (
    <div className="flex flex-col h-full w-full max-w-4xl mx-auto rounded-3xl overflow-hidden glass-panel">
      {/* Header */}
      <div className="flex justify-between items-center px-6 py-4 border-b border-white/5 bg-surface/80">
        <div className="flex items-center gap-3">
          <div className="relative flex h-3 w-3">
            <span className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${hasDocuments ? 'bg-green-400' : 'bg-primary'}`}></span>
            <span className={`relative inline-flex rounded-full h-3 w-3 ${hasDocuments ? 'bg-green-500' : 'bg-primary'}`}></span>
          </div>
          <h2 className="text-sm font-medium tracking-wide">
            {hasDocuments ? 'Ready to Answer' : 'Waiting for Documents'}
          </h2>
        </div>

        <button
          onClick={clearChat}
          className="p-2 bg-white/5 hover:bg-red-500/20 text-text-secondary hover:text-red-400 rounded-lg transition-colors border border-transparent hover:border-red-500/20 flex items-center gap-2 text-xs"
          title="Clear Conversation"
        >
          <FiTrash2 size={14} /> Clear
        </button>
      </div>

      {/* Messages Area */}
      <div className="flex-1 overflow-y-auto custom-scrollbar p-6 bg-gradient-to-b from-transparent to-surface/20">
        <div className="flex flex-col justify-end min-h-full">
          {messages.map((msg, index) => (
            <MessageBubble key={index} message={msg} />
          ))}

          {isLoading && (
            <div className="flex justify-start mb-4 px-4">
              <div className="flex items-center gap-3 bg-surfaceHighlight border border-white/5 rounded-2xl p-4 shadow-sm animate-pulse-slow">
                <div className="flex gap-1.5">
                  <div className="w-2 h-2 bg-primary rounded-full animate-[bounce_1s_infinite_0ms]"></div>
                  <div className="w-2 h-2 bg-primary rounded-full animate-[bounce_1s_infinite_200ms]"></div>
                  <div className="w-2 h-2 bg-primary rounded-full animate-[bounce_1s_infinite_400ms]"></div>
                </div>
                <span className="text-xs text-text-secondary">AI is thinking...</span>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} className="h-4" />
        </div>
      </div>

      {/* Input Area */}
      <div className="p-4 bg-surface/90 border-t border-white/5 backdrop-blur-xl">
        <form onSubmit={handleSend} className="relative flex items-center max-w-4xl mx-auto">
          <div className="absolute left-4 text-text-secondary">
            <FiCommand size={18} />
          </div>
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            disabled={isLoading}
            placeholder={hasDocuments ? "Ask a question about your document..." : "Upload a PDF first to start asking questions..."}
            className={`w-full bg-background border border-white/10 text-white text-sm rounded-2xl py-4 pl-12 pr-14 focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-transparent transition-all shadow-inner
              ${!hasDocuments && 'opacity-50 cursor-not-allowed'}
            `}
          />
          <button
            type="submit"
            disabled={isLoading || !input.trim()}
            className={`absolute right-2 p-2 rounded-xl transition-all duration-300 flex items-center justify-center
              ${input.trim() && !isLoading
                ? 'bg-primary text-white hover:bg-primary-dark shadow-[0_0_15px_rgba(103,58,183,0.5)] scale-100 opacity-100'
                : 'bg-white/5 text-text-secondary scale-95 opacity-50 cursor-not-allowed'}
            `}
          >
            <FiSend size={18} />
          </button>
        </form>
        <div className="text-center mt-3 text-[10px] text-text-secondary/50">
          DocuChat AI can make mistakes. Always verify important information from the sources.
        </div>
      </div>
    </div>
  );
};

export default ChatBox;
